# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.100
          
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 3.1.401
          
          
      - name: Install UpdateVersion
        run: dotnet tool install -g Monbsoft.UpdateVersion
 
      - name: Increment Patch Version
        run: update-version set  1.0.0-alpha.${{ github.run_number }}
    
      - name: Generate Package
        run: dotnet build CacheGroup.csproj --configuration Release
      
      
      - name: Publish to NuGet
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: CacheGroup.csproj
          VERSION_REGEX: '^\s*<Version>(.*)<\/Version>\s*$'
          TAG_FORMAT: '*'
          NUGET_KEY: ${{secrets.NUGET_KEY}}
